services:
  gateway:
    build:
      context: ./gateway
    environment:
      - MQ_PROTOCOL=amqp
      - MQ_HOSTNAME=rabbitmq
      - MQ_PORT=5672
      - MQ_USERNAME=defaultAdmin
      - MQ_PASSWORD=SomePassword
      - MQ_QUEUE=consumerTopic
    ports:
     - "8080:8080"
    environment:
     - PORT: "8080"

  service-auth:
    build:
      context: ./service-auth
    environment:
      - MQ_PROTOCOL=amqp
      - MQ_HOSTNAME=rabbitmq
      - MQ_PORT=5672
      - MQ_USERNAME=defaultAdmin
      - MQ_PASSWORD=SomePassword
      - MQ_QUEUE=consumerTopic
    depends_on:
      - rabbitmq
    restart: on-failure

  #service-analytics:
  #service-billing:
  #service-payments:
  
  rabbitmq:
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: defaultAdmin
      RABBITMQ_DEFAULT_PASS: SomePassword
    restart: always   
  dynamodb:
    image: instructure/dynamo-local-admin
    ports:
     - "8000:8000"
     - "8001:8001"
    restart: always

  #elasticsearch:

  neo4j:
    image: neo4j:5
    ports:
     - "7474:7474"
     - "7473:7473"
     - "7687:7687"
    environment:
     - NEO4J_AUTH=neo4j/password
    volumes:
     - .scripts/neo4j/import:/var/lib/neo4j/import
    restart: on-failure
    networks:
      - ezcharge
    command: >
      bash -c "
        /startup/docker-entrypoint.sh neo4j &  # Start Neo4j with the default entrypoint script
        sleep 20 &&  # Give Neo4j time to start
        until echo 'MATCH (n) RETURN n LIMIT 1;' | cypher-shell -u neo4j -p password;
        do echo 'Waiting for Neo4j to be ready...' && sleep 5;
        done &&
        cypher-shell -u neo4j -p password -f /var/lib/neo4j/import/import.cypher &&
        neo4j stop &&  # Stop the background Neo4j instance
        /startup/docker-entrypoint.sh neo4j
      "
  nginx:
    build:
      context: https://github.com/hodonsky/ocpp-broker.git#dev
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
     - NEO4J_HOST=neo4j
     - NEO4J_PORT=7474
     - NEO4J_USERNAME=neo4j
     - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    networks:
      ezcharge:
        ipv4_address: 172.20.0.5
  ocpp-service-1:
    build:
      args:
        - EXPOSE_PORT=6907
      context: https://github.com/hodonsky/ocpp-service.git#dev
      dockerfile: Dockerfile
    ports:
      - "6907"
    environment:
     - PORT=6907
     - IP=172.20.0.4
     - HOSTNAME=ocpp-service-1
    restart: on-failure
    depends_on:
     - neo4j
    networks:
      ezcharge:
        ipv4_address: 172.20.0.4

  pilot-charger:
    build:
      args:
        - EXPOSE_PORT=8180
      context: https://github.com/hodonsky/evse-app#dev
      dockerfile: Dockerfile
    ports:
     - "8180:8180"
    environment:
     - PORT=8180
     - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/nginx.crt
     - HEARTBEAT_TIMEOUT=30000
     - OCPP_HOST=nginx
     - OCPP_PORT=8443
     - OCPP_PATH=/evse/connect
     - PROTOCOL=wss
    extra_hosts:
      - "nginx:172.20.0.5"
      - "steve:172.20.0.21"
    networks:
      ezcharge:
        ipv4_address: 172.20.0.9

networks:
  ezcharge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
volumes:
  db-data:
    external: false